# Assignment for Maximum Covariance Analysis
### MPO 624 Spring 2018 Module 3
### Carli Merrick
#### 1.2 a.)

In [53]:
import numpy as np

In [57]:
#Define matrix
M=np.random.randint(10, size=(3,2)) #using integers btwn 0 and 10

print('Matrix= \n',M)

Matrix= 
 [[3 2]
 [6 1]
 [3 4]]


In [60]:
u,s,v = np.linalg.svd(M);
print ('u=',u);print('')
print ('v=',v);print('')
print ('s=',s)

u= [[-0.43935182  0.12902478 -0.88900089]
 [-0.70759631 -0.65938709  0.25400025]
 [-0.55342338  0.74064922  0.38100038]]

v= [[-0.88502227 -0.4655487 ]
 [-0.4655487   0.88502227]]

s= [ 8.16239743  2.89400557]


In [59]:
#Reconstruct matrix
SM=np.zeros([3,2])
SM[0:2,0:2]=np.diag(s)
RM=np.matmul(u,np.matmul(SM,v))
print('Reconstructed matrix=\n',RM)

Reconstructed matrix=
 [[ 3.  2.]
 [ 6.  1.]
 [ 3.  4.]]


#### 1.2 b.)

In [61]:
# 2x2
M=np.random.randint(10, size=(2,2))
covM=np.cov(M)
print('Using cov function: \n',covM);print('')

M1=np.mean(M,1)
M2=M-np.array([[M1[0]],[M1[1]]])
print ('Using DDT: \n',np.matmul(M2,M2.transpose()));print('')

u,s,vt=np.linalg.svd(M2)
SM=np.zeros([2,2])
SM[0:2,0:2]=np.diag(s)
T=np.matmul(u,SM);T1=np.matmul(SM.transpose(),u.transpose());
RM1=np.matmul(T,T1)
print('SVD Reconstructed Matrix: \n',RM1)

Using cov function: 
 [[  0.   0.]
 [  0.  18.]]

Using DDT: 
 [[  0.   0.]
 [  0.  18.]]

SVD Reconstructed Matrix: 
 [[  0.   0.]
 [  0.  18.]]


In [62]:
# 3x3
M=np.random.randint(10, size=(3,3))
covM=np.cov(M)
print('Using cov function: \n',covM);print('')
M1=np.mean(M,1)
M2=M-np.array([[M1[0]],[M1[1]],[M1[2]]])
print('Using DDT: \n',np.matmul(M2,M2.transpose()));print('')

u,s,vt=np.linalg.svd(M2)
SM=np.zeros([3,3])
SM[0:3,0:3]=np.diag(s)
T=np.matmul(u,SM);T2=np.matmul(SM.transpose(),u.transpose());
RM=np.matmul(T,T2)
print('SVD reconstructed Matrix: \n',RM)

Using cov function: 
 [[ 9.33333333  2.         -5.66666667]
 [ 2.          4.         -3.        ]
 [-5.66666667 -3.          4.33333333]]

Using DDT: 
 [[ 18.66666667   4.         -11.33333333]
 [  4.           8.          -6.        ]
 [-11.33333333  -6.           8.66666667]]

SVD reconstructed Matrix: 
 [[ 18.66666667   4.         -11.33333333]
 [  4.           8.          -6.        ]
 [-11.33333333  -6.           8.66666667]]


In [63]:
# covariance
EVAL,EVEC=np.linalg.eig(covM);
covRM=np.matmul(np.matmul(EVEC,np.diag(EVAL)),np.linalg.inv(EVEC))
print('cov matrix: \n',covRM)

cov matrix: 
 [[ 9.33333333  2.         -5.66666667]
 [ 2.          4.         -3.        ]
 [-5.66666667 -3.          4.33333333]]


In [67]:
# DTD
EVAL,EVEC=np.linalg.eig(np.matmul(M2.transpose(),M2));
covRM=np.matmul(np.matmul(EVEC,np.diag(EVAL)),np.linalg.inv(EVEC))
print ('DTD: \n',np.matmul(M2.transpose(),M2))
print('Cov matrix: \n',covRM)

DTD: 
 [[  4.88888889  -1.11111111  -3.77777778]
 [ -1.11111111  13.88888889 -12.77777778]
 [ -3.77777778 -12.77777778  16.55555556]]
Cov matrix: 
 [[  4.88888889  -1.11111111  -3.77777778]
 [ -1.11111111  13.88888889 -12.77777778]
 [ -3.77777778 -12.77777778  16.55555556]]


#### In part b., the eigen method returned two matrices, in contrast to part a., in which the SVD decomposition returned three.

#### Unlike the SVD, the eigen method can only be used with a square matrix because the eigenvalues are along the diagonal. Therefore, the eigen method would not be able to reconstruct the original 3x2 matrix but it works for the 2x2 and 3x3.

#### Using the 2x2 matrix, the reconstruction using the cov function, DDT, and SVD are equivalent but with a 3x3 matrix, the DDT and SVD return as double the value of the covariance matrix because DDT must be multiplied by 1/N-1.

#### The full data is reconstructed when using DTD instead of covariance.